### ISSUE TITLE
`describeNextReport` states there will be no velocities, not alway true?

### ISSUE THREAD

**Issue by orionarcher** [sef43/openmm-mdanalysis-reporter#4]
The `MDAnalysisReporter.describeNextReport` returns a tuple suggestions velocities will not be returned. However, same MDA formats (namely H5MD) return velocities [see here](https://github.com/MDAnalysis/mdanalysis/blob/develop/package%2FMDAnalysis%2Fcoordinates%2FH5MD.py#L1272). Thus, if `H5MD` is the extension, _I believe_, velocities will actually be reported.

Am I write about this? Writing velocities is a desirable behavior but should `describeNextReport` be modified?

**Comment by sef43** [comment]
Yes I believe you are correct, if velocities are being written to the trajectory file then the reporter should be asking openmm for up to date velocities via the describe next report tuple. 

is it possible to query the mda writer that gets chosen to see it will be writing velocities?

**Comment by orionarcher** [comment]
`is it possible to query the mda writer that gets chosen to see it will be writing velocities?`

I am not sure if we can query the MDA writer directly. A simple solution worth considering is to enumerate the reporters that can report velocities, which might be just `H5MD`. I've asked on the MDA Discord.

I'd be happy to implement the enumeration but a little hesitant to figure out querying the Writers.

**Comment by sef43** [comment]
yes enumeration would also be fine i think!

**Comment by orionarcher** [comment]
Great! Richard said TRR also reported velocities. I'll plan to just list H5MD and TRR for now and add others if I discover any. `writer_kwargs` will also be needed because they determine if velocities are reported, so I suggest adding this to PR #9?

**Comment by sef43** [comment]
yes if you can add to #9 that would be great! or if easier we can merge #9 first then add the velocity support later.  Let me know what you prefer.

**Comment by orionarcher** [comment]
I'll add it to #9 in the next few days.

**Comment by sef43** [comment]
closed by #9
